### ISSUE TITLE
Plugin not working anymore

### ISSUE THREAD

**Issue by tim010296** [Diginize/wp-vereinsflieger#19]
No error indication but login not working too! Maybe Vereinsflieger changed something within their API`?

**Comment by silviokennecke** [comment]
Refers to #18 
I’m going to fix it upcoming week.

**Comment by tim010296** [comment]
Hast Du bereits irgendeine Idee, woran es liegt? Solltest du Unterstützung gebrauchen können, gib gerne Bescheid.
