### ISSUE TITLE
Vereinsflieger.de REST API refused IPv6 requests

### ISSUE THREAD

**Issue by 4thCircleCorner** [Diginize/wp-vereinsflieger#20]
Currently REST API Interface of vereinsflieger.de will reject any calls using ipv6 address.
(already contacted vereinsflieger support)

In referent implementation by vereinslfieger.de you have to add in function "sendRequest"
`curl_setopt($CurlHandle, CURLOPT_IPRESOLVE, CURL_IPRESOLVE_V4);`
to force calls with ipv4

Hope this will also resolve some issues. ()

My webservers will use ipv6 address resolution by default.

**Comment by 4thCircleCorner** [comment]
Can be closed...IPV6 was blocked by vereinsflieger

**Comment by tim010296** [comment]
> Currently REST API Interface of vereinsflieger.de will reject any calls using ipv6 address.
> (already contacted vereinsflieger support)
> 
> In referent implementation by vereinslfieger.de you have to add in function "sendRequest"
> `curl_setopt($CurlHandle, CURLOPT_IPRESOLVE, CURL_IPRESOLVE_V4);`
> to force calls with ipv4
> 
> Hope this will also resolve some issues. ()
> 
> My webservers will use ipv6 address resolution by default.

Where exactly have you added the line to make IPV4 calls only?

**Comment by 4thCircleCorner** [comment]
hi,

here: [https://github.com/4thCircleCorner/wp-vereinsflieger-login/commit/41f3e25d2bec1b46e0df743c6221f69a770b88a0](https://github.com/4thCircleCorner/wp-vereinsflieger-login/commit/41f3e25d2bec1b46e0df743c6221f69a770b88a0)

**Comment by tim010296** [comment]
> hi,
> 
> here: [4thCircleCorner/wp-vereinsflieger-login@41f3e25](https://github.com/4thCircleCorner/wp-vereinsflieger-login/commit/41f3e25d2bec1b46e0df743c6221f69a770b88a0)

Thanks!
