### ISSUE TITLE
Plugin seems to have stopped working

### ISSUE THREAD

**Issue by tim010296** [Diginize/wp-vereinsflieger#22]
Ein Login ist nicht mehr möglich, Wordpress meldet bei jedem Versuch fehlerhafte Anmeldedaten.
An der Website wurde nichts verändert, das Plugin wurde bereits mehrfach neu installiert.

Eine Idee?

Fliegerische Grüße

**Comment by silviokennecke** [comment]
Ich habe es bei mir einmal getestet und keine Probleme feststellen können. Ich veröffentliche gleich ein Update, welches bei Problemen in der Vereinsflieger-Kommunikation dies anzeigt. Vielleicht kommen wir so bei der Lösung weiter. Ich würde mal blind vermuten, dass Vereinsflieger einen Error 503 zurückgibt, was auf aufgebrauchte Rate-Limits hinweist. In dem Fall müsstest du mit Jan einmal sprechen.

**Comment by Gerd-Q** [comment]
Hi Silvio,
ich habe die Version 1.1.0. ohne Probleme installiert bekommen. Der Login mit den Vereinsflieger Daten funktioniert leider immer noch nicht: LOGIN FAILED, PLEASE TRY AGAIN. Ich drücke die Daumen, dass Du nun die richtigen Info's bekommst.

Good Luck
Gerd

**Comment by tim010296** [comment]
> Ich habe es bei mir einmal getestet und keine Probleme feststellen können. Ich veröffentliche gleich ein Update, welches bei Problemen in der Vereinsflieger-Kommunikation dies anzeigt. Vielleicht kommen wir so bei der Lösung weiter. Ich würde mal blind vermuten, dass Vereinsflieger einen Error 503 zurückgibt, was auf aufgebrauchte Rate-Limits hinweist. In dem Fall müsstest du mit Jan einmal sprechen.

Danke dir! Tatsächlich zeigt es mir einen 503 Fehler an - sprich das Team von VF ansprechen? 
Gibt es eine Möglichkeit, einen solchen Fehler zukünftig zu vermeiden?
BG

**Comment by tim010296** [comment]
Ich habe bei unserer Seite mal alle Benutzer (die durch das Plugin kreiert wurden) gelöscht und das WP Fastest Cache Plugin deaktiviert. Nach Neuinstallation von WP Vereinsflieger funktionierte der Login wieder - vielleicht stand es damit in Zusammenhang.
VF selbst sagte auf Nachfrage, dass der AppKey nicht gesperrt war und auch nicht die IP von der die Anfragen kommen - wer weiß.
BG

**Comment by silviokennecke** [comment]
Hi Tim, danke für die Rückmeldung. Der Hinweis, dass ihr ein Cache-Plugin verwendet ist hilfreich. Ich schaue dann nochmal rein, vielleicht kann ich das so nachstellen.

**Comment by Spassbremse** [comment]
Hi Silvio, 
ich versuch gerade Gerd unter die Arme zu greifen. Der Login funktioniert leider immer noch nicht.
Kann man irgendwo sehen welche Daten vom Login an den VF geschickt werden, und was als Antwort zurück kommt?
Vielleicht ein Debug-Modus oder so, sonst ist das irgendwie stochern im Nebel.
Danke+Gruß
Olaf

**Comment by Spassbremse** [comment]
Ich habe jetzt mal ein paar Debug-Ausgaben eingebaut, es scheint schon vor dem eigentlichen Signin zu scheitern. Mehr als 503 wird auch nicht zurückgeliefert. Vielleicht hast Du eine Idee, wo ich drauf schauen soll? Das ganze ist leider etwas mühsam am Live-System. Ich werde nochmal prüfen ob AppKey und CID aktuell sind und ob uns der Vereinsflieger ausgesperrt hat.

14-Jun-2022 17:11:50 UTC] PHP Notice:  Array to string conversion in /home/wp/disk/wordpress/wp-content/plugins/wp-vereinsflieger/src/VereinsfliegerApi/Api/AuthApi.php on line 31
[14-Jun-2022 17:11:50 UTC] get AccessToken: https://www.vereinsflieger.de/interface/rest Array
[14-Jun-2022 17:11:50 UTC] Response AccessToken: 503
[14-Jun-2022 17:11:50 UTC] APIError: Login failed for user olaf/098f6bcd4621d373cade4e832627b4f6 :503

**Comment by Spassbremse** [comment]
Ich habe jetzt die vermutliche Ursache gefunden. Ein Bot-Netz versucht sich mit wechselnden IPs auf existierenden Acccounts einzuloggen. Aufgrund falscher Passworte führt das jedesmal zu einem Authentifizierungsrequest beim Vereinsflieger. Vermutlich führen diese Requests in Summe zur Blockade beim Vereinsflieger. 
Hier sollte man unterscheiden, ob es sich beim Login um einen originären WP-Account handelt um diese sinnlosen Requests zu unterbinden. Das wäre eigentlich ein neues Issue.
Eine Idee wäre den Usernamen des Vereinsfliegers mit einer RegEx zu prüfen, alles was nicht matched wird nicht über den Vereinsflieger authentifiziert.
