### ISSUE TITLE
WordPress sends 'password changed' e-mail on every login

### ISSUE THREAD

**Issue by uhertlein** [Diginize/wp-vereinsflieger#8]
Every time I login to our WordPress instance using wp-vereinsflieger with my VF credentials, WP sends me a "password changed" e-mail.

I assume this is because wp-vf resets my WP password after successfully authenticating against VF, but maybe there's some way to avoid this?
E.g. by checking the stored password hash against the current password hash and skip the update if they are identical?

**Comment by silviokennecke** [comment]
Hello @uhertlein, thank you for your report. I'm already aware of this problem. Please expect an update on Monday or Tuesday.

**Comment by silviokennecke** [comment]
Just so you know for future @uhertlein: About your suggestion with the password hash: Storing 'simple' password hashes is not recommended anymore. In case of a data leak attackers might compare them with so called rainbow tables. To prevent this, cryptographic functions are used nowadays. Also passwords get a "salt" so the outcoming hash is always a different one. A simple comparison is therefor not possible anymore. WordPress already changed their password hash and password validate functions a long time ago. If you want to read more about storing password secure and validate them later, I could recommend this article: https://auth0.com/blog/adding-salt-to-hashing-a-better-way-to-store-passwords/

**Comment by silviokennecke** [comment]
I just released the update. You can install it directly via the wordpress plugin directory

**Comment by uhertlein** [comment]
Thanks for the article; although I already knew about salt/pepper for hashed passwords, it was an interesting read.
